baseURL = "https://bd-evans.com/"
languageCode = "en-uk"
title = "Benjamin Evans"
theme = "alexa-portfolio"
enableRobotsTXT = true

[params]
	# favicon = "/images/fav.png"
	home_title = "Hi, I'm Benjamin Evans"
	home_subtitle = "Machine learning researcher"
	home_description = "I am interested in how the world works"
	github = "https://github.com/BDEvan5"
	linkedin = "https://www.linkedin.com/in/benjamin-david-evans/"
	location = "Stellenbosch, South Africa"
	email = "bdevans@sun.ac.za"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true